### ISSUE TITLE
7.2.0 fails to compile

### ISSUE THREAD

**Issue by svenstaro** [AcademySoftwareFoundation/openvdb#902]
This is on Arch Linux, gcc 10.2.0, boost 1.75.0. I'm trying to compile 7.2.0 (and also tried master). I get: 
[build.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5693255/build.txt)

If I compile with clang 11.0.0 instead, I get tons of these:
```
../openvdb/openvdb/./TypeList.h:318:36: error: unknown type name 'size_t'; did you mean 'std::size_t'?
```

**Comment by danrbailey** [comment]
Hi @svenstaro - thanks for reporting. We weren't aware that there were issues compiling OpenVDB on GCC 10. 

From the release notes (https://gcc.gnu.org/gcc-10/changes.html), it looks like this change is responsible:

> Reduced header dependencies, leading to faster compilation for some code.

I've fixed the issue by adding the missing header include and will submit a PR shortly to address this.

**Comment by danrbailey** [comment]
This PR resolves this issue - #905.

**Comment by svenstaro** [comment]
I confirm that this works fine. A patch release for this would be appreciated.

**Comment by danrbailey** [comment]
> I confirm that this works fine. A patch release for this would be appreciated.

I've just published a 7.2.1 patch release which includes this header fix.
