### ISSUE TITLE
Compiling fails with boost >=1.54

### ISSUE THREAD

**Issue by mojovski** [AcademySoftwareFoundation/openvdb#31]
It seems to me that the new openvdb version is not working with boost 1.54 and above.
The reason is the usage of the iostrems::filedescriptor method in boost.
I guess this is a boost bug, which was reported here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739908

So, compiling openvdb lib with the command 

```
g++ -pthread -O3 -DNDEBUG -I . -I .. -isystem /include -isystem /usr/include/OpenEXR -isystem /usr/include/tbb -isystem /rel/folio/log4cplus/log4cplus-1.0.3-latest/sys_include -DOPENVDB_USE_LOG4CPLUS -DOPENVDB_USE_GLFW_3 -o vdb_print cmd/openvdb_print/main.cc -I . \
        -ldl -lm -lz -Wl,-rpath,/usr/lib/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu/ -lHalf -Wl,-rpath,/usr/lib/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu/ -ltbb -Wl,-rpath,/usr/lib/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu/ -lboost_iostreams -lboost_system  -Wl,-rpath,/rel/folio/log4cplus/log4cplus-1.0.3-latest/library -L/rel/folio/log4cplus/log4cplus-1.0.3-latest/library -llog4cplus -lrt -ljemalloc \
        -Wl,-rpath,/tmp/OpenVDB/lib -L/home/user/projects/cpp/openvdb_github/openvdb libopenvdb.so.3.0.0
```

fails with

```
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor::seek(long, std::_Ios_Seekdir)'
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor::close()'
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(int, boost::iostreams::file_descriptor_flags)'
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor::write(char const*, long)'
libopenvdb.so.3.0.0: undefined reference to `boost::iostreams::file_descriptor::file_descriptor()'
```

When compiling to static libraries (setting make shared=no)
the error is

```
libopenvdb.a(Archive.o): In function `openvdb::v3_0_0::io::getErrorString(int)':
Archive.cc:(.text+0xf0c): undefined reference to `boost::system::generic_category()'
```

As for the linker libraries 

```
/usr/lib/x86_64-linux-gnu/
```

in my case,
this contains the required libraries:

```
libboost_iostreams.a
libboost_iostreams.so
libboost_iostreams.so.1.54.0
libboost_iostreams.so.1.55.0
```

**Comment by peterchencyc** [comment]
same question

**Comment by MatteoRagni** [comment]
Same error, but not related to the bug in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739908.
(I've tested it). 

Build fails because of this error, with **libboost 1.60.0-2**

**Comment by MatteoRagni** [comment]
Compile seems to succeed with libboost 1.49

**Comment by danrbailey** [comment]
Closing this as the minimum Boost version now supported is 1.61 so I assume this is now resolved. Please re-open if not.
